### ISSUE TITLE
Short-Code no longer working when TOC+ is disabled on all content-types

### ISSUE THREAD

**Issue by genyuz** [zedzedzed/table-of-contents-plus#164] opened 2024-02-21 12:19 UTC
I'm using TOC+ to show a table-of-contents on some specific posts only. Therefore I have disabled TOC+ everywhere and just include the [TOC]-short-code on some of the posts. This was working perfectly until **version 2311**. After the update, the short-code only works if TOC+ is activated for the specific content-type.

Maybe this issue can be fixed.

I have rolled back to version 2311 so far.

**Comment by zedzedzed** [comment] 2024-02-22 00:45
Thanks for reporting, this should be fixed with the 2402.1 release

**Comment by genyuz** [comment] 2024-02-22 07:45
> Thanks for reporting, this should be fixed with the 2402.1 release

Unfortunately it is not. I have disabled TOC+ for all content-types and have the short-code on some single posts but after the update to 2402.1 (which I made some minutes ago) the table-of-contents is not shown in these posts. I will now roll-back again to version 2311.

**Comment by zedzedzed** [comment] 2024-02-22 09:59
Hmm that's odd. For my testing, I had turned off all content types for auto insertion and solely relied on using the `[toc]` shortcode within the content. For me it worked when there were enough headings on the page. Eg I created a 2 heading  post but it wouldn't initially create the TOC until I changed the minimum heading number from 4 to 2. Have you tried this yet? Do you have any excluded headings or heading levels in your settings?

**Comment by zedzedzed** [comment] 2024-02-22 10:12
I should have mentioned that I'm not 100% confident what the cause is, but the above is a good place to start.

I have just tried downgrading to 2311 and applied the same test as above (no auto insertions) relying on the shortcode. It behaved the same, the TOC didn't appear under there was enough headings.

**Comment by genyuz** [comment] 2024-02-22 11:51
I currently have version 2311 installed, which works as expected. The settings looks like this:

![image](https://github.com/zedzedzed/table-of-contents-plus/assets/26007827/7c4bb963-71d3-4d7b-a782-8a49fc764288)

And one of the pages, I am talking about is https://karate-bannewitz.de/2024/01/01/erste-dojo-info-2024/

There are 7 h2-headlines on this page and you can see, that the table-of-contents is displayed as it should. But when I update to the latest version (2402.1), with the same settings it disappears.

**Comment by zedzedzed** [comment] 2024-02-23 01:26
Thank you for the screenie and link. I've copied your settings and content to my dev site to try to replicate your problem. So far I haven't been able to as the TOC appears on my dev environment with your content and settings.

Note that I'm not running WP Super Cache or any other caching plugin but I immediately saw in the source that TOC+ thought it was an older version despite you running 2311: 

`/table-of-contents-plus/front.min.js?ver=2309`

This told me I hadn't been keeping my internal versioning up to date so I've fixed that with https://github.com/zedzedzed/table-of-contents-plus/commit/13721f9f6f08d45d22939193a18bbf62b46fd965

I think internal versioning could play a key part with caching.

Do you provide any shortcode overrides or is it just `[toc]`?

Are you able to try the changes from https://github.com/zedzedzed/table-of-contents-plus/archive/refs/heads/main.zip and after enabling, check the front end HTML source to make sure `front.min.js?ver=2402.1` appears and that WP Super Cache has updated.

**Comment by zedzedzed** [comment] 2024-02-24 10:01
Great to hear! I'll tag a new release through the WordPress plugin system shortly with only this change.

**Closed by zedzedzed** 2024-02-24 10:01 UTC
